name: scan goose new release

on:
  workflow_dispatch:

jobs:
  scan:
    name: Scan Goose new release
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - id: goose_last_version
        name: Get list goose version
        uses: pozetroninc/github-action-get-latest-release@v0.8.0
        with:
          repository: pressly/goose

      - name: Run tests on new goose version
        run: make test GOOSE_VERSION=${{ steps.goose_last_version.outputs.release }}
